@startuml

hide empty methods
hide empty attributes
'left to right direction
skinparam classAttributeIconSize 0

class ShipOccupancyRatesController{
- getShipOccupancyRateByCargoManifestID(cargoManifestID)
- calculateOccupancyRate(maxCapacity, initialNumContainers, addedContainersNum, removedContainersNum)
}

class ShipStore{
- getMaxCapacityByMmsi(mmsi)
}

class ShipTripStore{
- getMmsiOfChosenShip(databaseConnection, cargoManifestID)
- getShipTripByCargoManifestID(cargoManifestID)
- getInitialNumContainersByShipTripID(shipTripID)
- getLoadingCargoManifestIDByShipTripID(shipTripID)
- getUnloadingCargoManifestIDByShipTripID(shipTripID)
}

class CargoManifestStore{
- getNumOfAddedContainersByLoadingCargoManifestID(loadingCargoManifestID)
- getNumOfRemovedContainersByUnloadingCargoManifestID(unloadingCargoManifestID)
}

class Company{
- getShipStore()
}

class Ship {
- MMSI
- cargo
}

'class ShipsStore{
'- findShipByAnyCode(code)
'}

'class ShipsBST{
'- findShipByMmsi(MMSI)
'}

'class BST{}

'preciso do cargo manifest com o id
'preciso da ship trip pq ela contem o cargo manifest e o mmsi para o ship
'vou procurar o ship com o mmsi da ship trip

ShipOccupancyRatesController ..> Company
ShipOccupancyRatesController ..> ShipStore
ShipOccupancyRatesController ..> ShipTripStore
ShipOccupancyRatesController ..> CargoManifestStore
Company "1" -- "1" ShipStore : uses >
ShipStore "1" -- "1..*" Ship : uses >

@enduml