@startuml
autonumber
'hide footbox
actor "Traffic Manager" as TM
participant ":ImportShipsUI  " as UI
participant ":ImportShipsController" as CTRL
participant ":Company" as CMP
participant ":ShipsBST" as SBST
participant ":Ship" as SHIP
participant ":PositionBST" as PBST
participant ":Position" as POS
participant ":VesselTypeStore" as VTSTR
participant ":VesselType" as VT

'FALTAM AS VALIDAÇÕES

activate TM
TM -> UI : asks to import ships from a text file into a BST
activate UI
UI --> TM : asks for data(i.e., file path)
deactivate UI

TM -> UI : types requested data
activate UI
UI -> CTRL : importShips(file path)
activate CTRL
CTRL -> CMP : shipsBST = getShipsBST()
activate CMP
CMP --> CTRL : shipsBST
deactivate CMP
CTRL -> CMP : vesselTypeStore = getVesselTypeStore()
activate CMP
CMP --> CTRL : vesselTypeStore
deactivate CMP
loop for each line of the file
CTRL -> SBST : ship = getShipByMMSI(mmsi)
activate SBST
SBST --> CTRL : ship
deactivate SBST
alt if ship == null
CTRL -> VTSTR : vesselType = getVesselTypeByID(vesselTypeID)
activate VTSTR
VTSTR --> CTRL : vesselType
deactivate VTSTR
alt if vesselType == null
CTRL -> VTSTR : createVesselType(vesselTypeID, length, width, maxCapacity)
activate VTSTR
VTSTR --> VT : create(vesselTypeID, length, width, maxCapacity)
activate VT
deactivate VT
deactivate VTSTR
end
CTRL -> SBST : createShip(mmsi, imo, callSign, shipName, draft, vesselTypeID)
activate SBST
SBST -> VTSTR : vesselType = getVesselTypeByID(vesselTypeID)
activate VTSTR
VTSTR --> SBST : vesselType
deactivate VTSTR
SBST -> PBST** : create()
activate PBST
PBST --> SBST : shipPositions
deactivate PBST
SBST -> SHIP : create(mmsi, imo, callSign, shipName, draft, shipPositions, vesselType)
activate SHIP
deactivate SHIP
deactivate SBST
end
CTRL -> PBST : createPosition(baseDateTime, latitude, longitude, sog, cog, heading, transceiver)
activate PBST
PBST -> POS : create(baseDateTime, latitude, longitude, sog, cog, heading, transceiver)
activate POS
deactivate POS
deactivate PBST
end
CTRL --> UI : result
deactivate CTRL
UI --> TM : informs of operation success or fail
deactivate UI
deactivate TM

@enduml
