@startuml

skinparam classAttributeIconSize 0


class Ship {
    -mmmsiCode
    -shipName
    -imoCode
    -callSignId
    -currentCapacity /'added by us'/
    -draft

    -getMMSI()
}

class ShipPosition {
    -baseDateTime
    -latitude
    -longitude
    -sog
    -cog
    -heading
    -position
    -transceiver
}

class ShipStore {
    -getShipsBstMmsi()
}


class AllShipUI {}

class AllShipMMSIController {
    -sortedByTravelledDistance()
    -sortedByTotalMovements()
}

class ShipsBST{
    -getAllShips()
    -sortedByTravelledDistance()
    -sortByTotalMovements()
}

class PositionBST{
    -size()
    -getTotalDistance()
    -size()
    -getDeltaDistance()
}
class Company {
    -getShipStore()
}


Company "1" -- "1" ShipStore : uses >
ShipStore ..> ShipsBST
ShipsBST "1" -- "1..*" Ship : owns >
TopNUI ..> TopNController
TopNController ..> ShipsBST
TopNController ..> Company
ShipsBST ..> Ship
PositionBST ..> ShipPosition
Company ..> Ship


@enduml