@startuml

skinparam classAttributeIconSize 0


class Ship {
    -mmmsiCode
    -shipName
    -imoCode
    -callSignId
    -currentCapacity /'added by us'/
    -draft
}

class ShipPosition {
    -baseDateTime
    -latitude
    -longitude
    -sog
    -cog
    -heading
    -position
    -transceiver
    -getSOG()
}


class TopNUI {}

class TopNController {
    -getShipByBaseDateTime(initialBaseDate, finalBaseDate)
    -sortNShips(shipList, N)
    -getShipWithMean(sortedShips)
}

class ShipsBST{
    -getShipByBaseDateTime(initialBaseDate, finalBaseDate)
    -sortNShips(shipList, N)
    -getShipWithMean(sortedShips)
}

class PositionBST{
    -getShipBaseDateTime(code)
    -getMeanSOG(code)
    -getTotalDistance()
}
class Company {
    -getShipsBST()
}


Company "1" -- "1" ShipsBST : uses >
ShipsBST ..> PositionBST
ShipsBST "1" -- "1..*" Ship : owns >
TopNUI ..> TopNController
TopNController ..> ShipsBST
TopNController ..> Company
ShipsBST ..> Ship
PositionBST ..> ShipPosition
Company ..> Ship


@enduml