@startuml
skinparam classAttributeIconSize 0

class Company{
    +getShipBst()
}

class Ship {
    +getName()
    +getMovements()
}

class ShipsBST{
    +findShipByMmsi(MMSI)
}

class ShipPosition{
    +getLatitude()
    +getLongitude()
    +getBaseTime()
    +getSog()
    +getCog()
}

class ShipMovementsBST {
    +getStartDate()
    +getEndDate()
    +getMaxSog()
    +getMeanSog()
    +getMeanCog()
    +getDepartLatitude()
    +getDepartLongitude()
    +getArrivalLatitude()
    +getArrivalLongitude()
    +getTravelDistance()
    +getDeltaDistance()
}


class MovementSummaryController {
+getShipMovementSummary(MMSI)
}


MovementSummaryController ..> Company
MovementSummaryController ..> ShipsBST
Company "1" --> "*" Ship : knows
Company "1" -- "1" ShipsBST : uses >
ShipsBST ..> Ship
Ship "1" -- "*" ShipPosition : sends >
Ship "1" -- "1" ShipMovementsBST : uses >
ShipMovementsBST ..> ShipPosition
@enduml
