@startuml
autonumber
'hide footbox
actor "TrafficManager" as RC

participant ":TrafficManagerUI" as UI
participant ":MovementSummaryController" as CTRL
participant ": Company" as CP
participant ": ShipsBST" as CS
participant ": MovementsSummaryDTO" as CL


activate RC
RC -> UI : asks to make a summary of a ship's movement
activate UI
UI --> RC : requests data (MMSI)
deactivate UI

RC -> UI : types requested data
activate UI

UI -> CTRL : getShipMovementSummary(MMSI)

CTRL -> CP : store = getShipsBST()
activate CP
deactivate CP
activate CTRL
CTRL -> CS : cl = getShipMovementSummary(MMSI)
activate CS
CS --> CS : ship = findShip(MMSI)
CS --> CS : name = ship.getName()
CS --> CS : startDate = ship.getStartDate()
CS --> CS : endDate = ship.getEndDate()
CS --> CS : movements = ship.getMovements()
CS --> CS : maxSog = movements.getMaxSog()
CS --> CS : meanSog = movements.getMeanSog()
CS --> CS : meanCog = movements.getMeanCog()
CS --> CS : departLatitute = movements.getDepartLatitude()
CS --> CS : departLongitude = movements.getDepartLongitude()
CS --> CS : arrivalLatitude = movements.getArrivalLatitude()
CS --> CS : arrivalLongitude = movements.getArrivalLongitude()
CS --> CS : travelledDistance = movements.getTravelledDistance()
CS --> CS : deltaDistance = movements.getDeltaDistance()


CS -->  CL** : summaryDto = create(MMSI, name, startDate, endDate, movement, maxSog, meanSog, meanCog, departLatitute\n, departLongitude, arrivalLatitude, arrivalLongitude, travelledDistance, deltaDistance)
deactivate CL
CS --> CTRL : summaryDto
deactivate CS
CTRL --> UI : summaryDto
deactivate CTRL

UI --> RC : returns the summary of the ships movements
deactivate CS
deactivate UI


@enduml