@startuml
'https://plantuml.com/class-diagram

/'class Company{

}'/

class Ship{
    **IMO**
    MMSI
    CallSignId
    ShipName
    VesselTypeID FK
    NumEnergyGenerators
    GeneratorsPower
    CurrentCapacity
    Draft
}

class VesselType{
    **VesselTypeID**
    Length
    Width
    maxCapacity
}

class ShipPosition{
    **BaseDateTime**
    **Latitude**
    **Longitude**
    IMO FK
    Sog
    Cog
    Heading
    Position
    Transceiver
}

class Container{
    **ContainerID**
    Payload
    Tare
    Gross
    CheckDigit
    ISOCode
    temperatureKept
}
/'refrigeration state is ambigous'/

/'manifest type(loading, unloading) changes its values'/
class CargoManifest{
    **CargoManifestID**
    **ContainerID**FK
    IMO FK
    TypeOfTransport
}

class PositionInVehicule{
    **CargoManifestID**FK
    **ContainerID**FK
    ContainerPositionInVehiculeX
    ContainerPositionInVehiculeY
    ContainerPositionInVehiculeZ
}

class Port {
    **Identification**
    Name
    LocationLongitude FK
    LocationLatitude FK
}

class Warehouse {
    **Identification**
    Name
    LocationLongitude FK
    LocationLatitude FK
}

class Country{
    **Country**
    Continent
}

class PlaceLocation{
    **locationLatitude**
    **LocationLongitude**
    Country FK
}


class Truck{
    truckID
}


Ship "1" -- "1..*" Container : transports >
Container "1" -- "1" PositionInVehicule
Ship "1" -- "1" ShipPosition
Ship "*" -- "1" VesselType
Ship "1" -- "1..*" CargoManifest
CargoManifest "1" -- "1..*" Container
Truck "1" -- "1..*" CargoManifest
Truck "*" -- "1" Container
Port "1" -- "1" PlaceLocation
WareHouse "1" -- "1" PlaceLocation
PlaceLocation "*" -- "1" Country
Port "1" -- "*" CargoManifest
WareHouse "1" -- "*" CargoManifest
/'Relacoes N para N, falta relacao'/
Truck "1..*" -- "1..*" Warehouse
Ship "1..*" -- "1..*" Port

@enduml